import 'package:flutter/material.dart';

/// Dəstəklənən dillərin modeli
class AppLanguage {
  final String code;
  final String name;
  final String nativeName;
  final String flag;

  const AppLanguage({
    required this.code,
    required this.name,
    required this.nativeName,
    required this.flag,
  });
}

/// AppStrings - Çoxdilli tərcümə və mətn idarəetmə sistemi.
/// Varsayılan dil qlobal standart olan İngilis dilidir (en).
class AppStrings {
  static const List<AppLanguage> supportedLanguages = [
    AppLanguage(code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸'),
    AppLanguage(code: 'az', name: 'Azerbaijani', nativeName: 'Azərbaycan', flag: '🇦🇿'),
    AppLanguage(code: 'tr', name: 'Turkish', nativeName: 'Türkçe', flag: '🇹🇷'),
    AppLanguage(code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸'),
    AppLanguage(code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺'),
    AppLanguage(code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪'),
  ];

  static String currentLocale = 'en';

  static void setLocale(String code) {
    if (supportedLanguages.any((lang) => lang.code == code)) {
      currentLocale = code;
    } else {
      currentLocale = 'en';
    }
  }

  static AppLanguage get currentLanguage {
    return supportedLanguages.firstWhere(
      (lang) => lang.code == currentLocale,
      orElse: () => supportedLanguages.first,
    );
  }

  static String get(String key) {
    final translations = _localizedValues[currentLocale] ?? _localizedValues['en']!;
    return translations[key] ?? _localizedValues['en']![key] ?? key;
  }

  // Tərcümə bazası
  static final Map<String, Map<String, String>> _localizedValues = {
    // -------------------------------------------------------------
    // ENGLISH (DEFAULT / PRIMARY)
    // -------------------------------------------------------------
    'en': {
      // Navigation
      'nav_scanner': 'Scan',
      'nav_generator': 'Generate',
      'nav_history': 'History',
      'nav_settings': 'Settings',

      // Scanner Screen
      'scanner_title': 'QR Scanner',
      'scanner_pick_gallery': 'Pick from gallery',
      'scanner_flash': 'Flashlight',
      'scanner_switch_camera': 'Switch camera',
      'scanner_no_qr_in_image': 'No QR code found in the selected image',
      'scanner_error_reading_image': 'Error reading image: ',
      'scanner_result_title': 'QR Code Detected!',
      'scanner_security_clean': 'SECURITY AUDIT: Clean & Safe',
      'scanner_security_suspicious': 'WARNING: Suspicious Link',
      'scanner_security_blocked': 'DANGER: Execution Blocked',
      'scanner_rescan': 'Scan Again',
      'scanner_copy': 'Copy',
      'scanner_share': 'Share',
      'scanner_perm_denied': 'Camera permission was denied.\nPlease enable camera permission in device settings.',
      'scanner_cam_unsupported': 'Camera is unsupported or not available on this device.',
      'scanner_cam_error': 'Camera failed to initialize or is being used by another app.',
      'scanner_retry': 'Try Again',

      // Primary Actions
      'action_open_browser': 'Open in Browser',
      'action_open_whatsapp': 'Chat on WhatsApp',
      'action_call': 'Make Call',
      'action_send_email': 'Send Email',
      'action_send_sms': 'Send SMS',
      'action_copy_wifi': 'Copy Wi-Fi Password',
      'action_copy_text': 'Copy Text',
      'action_blocked_btn': 'Dangerous: Execution Blocked',
      'action_execute': 'Execute / Open',
      'action_copied': 'Copied to clipboard!',
      'action_wifi_copied': 'Wi-Fi password copied!',
      'action_wifi_info_copied': 'Wi-Fi details copied!',
      'action_link_error': 'Could not open link',
      'action_call_error': 'Could not initiate call',
      'action_email_error': 'No email app found',
      'action_sms_error': 'No SMS app found',
      'action_only_https': 'For security, only HTTPS/HTTP links can be opened',

      // QR Types
      'type_text': 'Plain Text',
      'type_url': 'Website Link',
      'type_whatsapp': 'WhatsApp Chat',
      'type_wifi': 'Wi-Fi Network',
      'type_phone': 'Phone Number',
      'type_email': 'Email Address',
      'type_sms': 'SMS Message',

      // Generator Screen
      'gen_title': 'QR Generator',
      'gen_enter_details': 'Fill in the field above to generate a QR code',
      'gen_color_picker': 'QR Code Color:',
      'gen_save': 'Save to History',
      'gen_share_img': 'Share Image',
      'gen_saved_success': 'QR Code added to history!',
      'gen_blocked_title': 'Generation Blocked',
      'gen_blocked_save_msg': 'Security Block: Cannot save dangerous content!',
      'gen_blocked_share_msg': 'Security Block: Cannot share malicious content: ',
      'gen_status_clean': 'Security Check: Clean & Safe',
      'gen_status_suspicious': 'Suspicious Content (Proceed with caution)',
      'gen_input_text_label': 'Enter text',
      'gen_input_text_hint': 'e.g., Hello, this is my QR code!',
      'gen_input_url_label': 'Website URL',
      'gen_input_url_hint': 'https://example.com',
      'gen_input_wa_phone': 'WhatsApp Number (with country code)',
      'gen_input_wa_msg': 'Pre-filled Message (optional)',
      'gen_input_wa_msg_hint': 'Hello! Inquiring about your listing...',
      'gen_input_wifi_ssid': 'Network Name (SSID)',
      'gen_input_wifi_pass': 'Password',
      'gen_input_wifi_security': 'Security Type',
      'gen_input_phone': 'Phone Number',
      'gen_input_email': 'Email Address',
      'gen_input_subject': 'Subject',
      'gen_input_sms': 'SMS Message',
      'gen_wifi_open': 'Open (No password)',

      // History Screen
      'history_title': 'History',
      'history_clear_all_tooltip': 'Clear history',
      'history_clear_dialog_title': 'Clear History?',
      'history_clear_dialog_desc': 'All saved QR codes will be deleted. This action cannot be undone.',
      'history_cancel': 'Cancel',
      'history_delete': 'Delete',
      'history_search_hint': 'Search in history...',
      'history_filter_all': 'All',
      'history_filter_scanned': 'Scanned',
      'history_filter_generated': 'Generated',
      'history_filter_favorites': 'Favorites',
      'history_empty_title': 'No QR codes yet',
      'history_empty_search_title': 'No matching results found',
      'history_empty_subtitle': 'Scan a QR code or create a new one',
      'history_empty_search_subtitle': 'Try searching for different keywords',
      'history_item_deleted': 'Item deleted',
      'history_undo': 'Undo',
      'history_badge_scanned': '• Scanned',
      'history_badge_generated': '• Generated',

      // Settings Screen
      'settings_title': 'Settings',
      'settings_section_appearance': 'APPEARANCE & LANGUAGE',
      'settings_theme_mode': 'Appearance Mode',
      'settings_language': 'Language / Dil',
      'settings_section_storage': 'STORAGE & DATA',
      'settings_saved_items': 'Saved QR Codes',
      'settings_items_count': 'items saved',
      'settings_clear_btn': 'Clear',
      'settings_cleared_msg': 'History cleared',
      'settings_section_security': 'SECURITY & AUDIT',
      'settings_malware_protection': 'Malware & Threat Protection',
      'settings_malware_active': 'Active (.apk, .exe and malicious payloads blocked)',
      'settings_audit_report': 'Security Audit Report',
      'settings_audit_report_sub': 'View safety rules and protection mechanisms',
      'settings_section_about': 'ABOUT',
      'settings_version': 'Version',
      'settings_privacy_policy': 'Privacy Policy',
      'settings_privacy_policy_sub': 'Data security and permission guidelines',
      'settings_theme_dialog_title': 'Choose Appearance Mode',
      'settings_theme_system': 'System Default (Automatic)',
      'settings_theme_light': 'Light Mode',
      'settings_theme_dark': 'Dark Mode',
      'settings_lang_dialog_title': 'Choose Language',
      'settings_close': 'Close',

      // Security Dialogs & Audit
      'sec_dialog_title': 'Security Audit',
      'sec_dialog_intro': 'Real-time protection parameters active on this device:',
      'sec_item_malware_title': 'Malware & Executable Filtering',
      'sec_item_malware_desc': '.apk, .exe, .bat, .vbs, .sh and 25+ executable extensions are strictly blocked from QR generation and opening.',
      'sec_item_script_title': 'Script & XSS Protection',
      'sec_item_script_desc': 'Dangerous schemes such as javascript:, data:, file: and embedded code injections are banned.',
      'sec_item_scanner_title': 'Scanner Risk Evaluation',
      'sec_item_scanner_desc': 'Every scanned code is verified in real-time with instant warning prompts for suspicious URLs.',
      'sec_item_dos_title': 'DoS & Buffer Overflow Prevention',
      'sec_item_dos_desc': 'A strict 2,953 character threshold prevents memory overflow or application freezing attacks.',
      'sec_item_privacy_title': 'Zero-Knowledge Local Storage',
      'sec_item_privacy_desc': 'All QR code history and generated codes stay 100% on your device (SharedPreferences). No external servers.',
      'sec_blocked_dialog_title': 'Security Rule Triggered',
      'sec_blocked_dialog_rule': 'Execution was blocked according to built-in security policies.',
      'sec_suspicious_dialog_title': 'Suspicious Link Warning',
      'sec_suspicious_dialog_btn_back': 'Go Back',
      'sec_suspicious_dialog_btn_proceed': 'Proceed Anyway',
      'sec_understood': 'Understood',

      // Ad banner
      'ad_tag': 'SPONSOR',
      'ad_title_security': 'QR & Barcode Security',
      'ad_sub_security': 'Protect your device from malware & phishing links 100%.',
      'ad_title_premium': 'Fast & Offline QR Suite',
      'ad_sub_premium': 'Create custom colorful QR codes with high precision.',
      'ad_cta_learn': 'Learn More',
      'ad_cta_explore': 'Explore',
      'ad_close_tooltip': 'Hide banner',
    },

    // -------------------------------------------------------------
    // AZERBAIJANI
    // -------------------------------------------------------------
    'az': {
      // Navigation
      'nav_scanner': 'Skaner',
      'nav_generator': 'Generator',
      'nav_history': 'Tarixçə',
      'nav_settings': 'Tənzimləmələr',

      // Scanner Screen
      'scanner_title': 'QR Skaner',
      'scanner_pick_gallery': 'Qalereyadan seç',
      'scanner_flash': 'Fənər',
      'scanner_switch_camera': 'Kameranı dəyiş',
      'scanner_no_qr_in_image': 'Seçilmiş şəkildə heç bir QR kod tapılmadı',
      'scanner_error_reading_image': 'Şəkil oxunarkən xəta: ',
      'scanner_result_title': 'QR Kod Oxundu!',
      'scanner_security_clean': 'TƏHLÜKƏSİZLİK AUDİTİ: Təmiz',
      'scanner_security_suspicious': 'DİQQƏT: Şübhəli Bağlantı',
      'scanner_security_blocked': 'TƏHLÜKƏLİ: İcra Bloklandı',
      'scanner_rescan': 'Yenidən Skan Et',
      'scanner_copy': 'Kopyala',
      'scanner_share': 'Paylaş',
      'scanner_perm_denied': 'Kamera icazəsi verilməyib.\nZəhmət olmasa tətbiq tənzimləmələrindən kamera icazəsini aktivləşdirin.',
      'scanner_cam_unsupported': 'Bu cihazda kamera dəstəklənmir və ya mövcud deyil.',
      'scanner_cam_error': 'Kamera hazır deyil və ya başqa tətbiq tərəfindən istifadə olunur.',
      'scanner_retry': 'Yenidən yoxla',

      // Primary Actions
      'action_open_browser': 'Brauzerdə Aç',
      'action_open_whatsapp': 'WhatsApp-da Yaz',
      'action_call': 'Zəng Et',
      'action_send_email': 'Email Göndər',
      'action_send_sms': 'SMS Göndər',
      'action_copy_wifi': 'Wi-Fi Şifrəsini Kopyala',
      'action_copy_text': 'Mətni Kopyala',
      'action_blocked_btn': 'Təhlükəli: İcra Bloklanıb',
      'action_execute': 'İcra et / Aç',
      'action_copied': 'Mətn kopyalandı!',
      'action_wifi_copied': 'Wi-Fi şifrəsi kopyalandı!',
      'action_wifi_info_copied': 'Wi-Fi məlumatı kopyalandı!',
      'action_link_error': 'Link açıla bilmədi',
      'action_call_error': 'Zəng edilə bilmədi',
      'action_email_error': 'Email proqramı tapılmadı',
      'action_sms_error': 'SMS proqramı tapılmadı',
      'action_only_https': 'Təhlükəsizlik səbəbilə yalnız HTTPS/HTTP linkləri açıla bilər',

      // QR Types
      'type_text': 'Düz Mətn',
      'type_url': 'Veb Sayt',
      'type_whatsapp': 'WhatsApp',
      'type_wifi': 'Wi-Fi',
      'type_phone': 'Telefon',
      'type_email': 'Email',
      'type_sms': 'SMS',

      // Generator Screen
      'gen_title': 'QR Generator',
      'gen_enter_details': 'QR kod yaratmaq üçün yuxarıdakı xananı doldurun',
      'gen_color_picker': 'QR Kodun Rəngi:',
      'gen_save': 'Yadda saxla',
      'gen_share_img': 'Şəkli paylaş',
      'gen_saved_success': 'QR Kod tarixçəyə əlavə edildi!',
      'gen_blocked_title': 'Yaradılma Bloklandı',
      'gen_blocked_save_msg': 'Təhlükəsizlik Bloklaması: Təhlükəli məzmun yadda saxlanıla bilməz!',
      'gen_blocked_share_msg': 'Zərərli məzmun təhlükəsizlik səbəbilə paylaşıla bilməz: ',
      'gen_status_clean': 'Təhlükəsizlik Yoxlanışı: Təmiz',
      'gen_status_suspicious': 'Şübhəli Bağlantı (Diqqətli olun)',
      'gen_input_text_label': 'Mətn daxil edin',
      'gen_input_text_hint': 'Məsələn: Salam, bu mənim ilk QR kodumdur!',
      'gen_input_url_label': 'Veb sayt ünvanı',
      'gen_input_url_hint': 'https://example.com',
      'gen_input_wa_phone': 'WhatsApp Nömrəsi (Ölkə kodu ilə)',
      'gen_input_wa_msg': 'Hazır mesaj (İstəyə görə)',
      'gen_input_wa_msg_hint': 'Salam! Sizin elanla bağlı yazıram...',
      'gen_input_wifi_ssid': 'Şəbəkə adı (SSID)',
      'gen_input_wifi_pass': 'Şifrə',
      'gen_input_wifi_security': 'Təhlükəsizlik növü',
      'gen_input_phone': 'Telefon nömrəsi',
      'gen_input_email': 'Email ünvanı',
      'gen_input_subject': 'Mövzu (Subject)',
      'gen_input_sms': 'SMS mesajı',
      'gen_wifi_open': 'Açıq (Şifrəsiz)',

      // History Screen
      'history_title': 'Tarixçə',
      'history_clear_all_tooltip': 'Tarixçəni təmizlə',
      'history_clear_dialog_title': 'Tarixçəni təmizlə?',
      'history_clear_dialog_desc': 'Bütün saxlanılmış QR kodlar silinəcək. Bu əməliyyatı geri qaytarmaq mümkün deyil.',
      'history_cancel': 'İmtina',
      'history_delete': 'Sil',
      'history_search_hint': 'Tarixçədə axtar...',
      'history_filter_all': 'Hamısı',
      'history_filter_scanned': 'Skan edilənlər',
      'history_filter_generated': 'Yaradılanlar',
      'history_filter_favorites': 'Sevimlilər',
      'history_empty_title': 'Hələ heç bir QR kod yoxdur',
      'history_empty_search_title': 'Heç bir nəticə tapılmadı',
      'history_empty_subtitle': 'QR kod skan edin və ya yeni QR kod yaradın',
      'history_empty_search_subtitle': 'Fərqli axtarış sözü yoxlayın',
      'history_item_deleted': 'Element silindi',
      'history_undo': 'Geri qaytar',
      'history_badge_scanned': '• Skan edilib',
      'history_badge_generated': '• Yaradılıb',

      // Settings Screen
      'settings_title': 'Tənzimləmələr',
      'settings_section_appearance': 'GÖRÜNÜŞ VƏ DİL',
      'settings_theme_mode': 'Görünüş rejimi',
      'settings_language': 'Dil / Language',
      'settings_section_storage': 'YADDAŞ VƏ TARİXÇƏ',
      'settings_saved_items': 'Saxlanılmış QR kodlar',
      'settings_items_count': 'element saxlanılıb',
      'settings_clear_btn': 'Təmizlə',
      'settings_cleared_msg': 'Tarixçə təmizləndi',
      'settings_section_security': 'TƏHLÜKƏSİZLİK VƏ AUDİT',
      'settings_malware_protection': 'Zərərli Proqram Mühafizəsi',
      'settings_malware_active': 'Aktiv (.apk, .exe və skriptlər bloklanır)',
      'settings_audit_report': 'Təhlükəsizlik Auditi Hesabatı',
      'settings_audit_report_sub': 'Parametrlər və audit nəticələrinə bax',
      'settings_section_about': 'HAQQINDA',
      'settings_version': 'Versiya',
      'settings_privacy_policy': 'Məxfilik Siyasəti (Privacy Policy)',
      'settings_privacy_policy_sub': 'Məlumatlarınızın təhlükəsizliyi və icazələr haqqında',
      'settings_theme_dialog_title': 'Görünüş rejimini seçin',
      'settings_theme_system': 'Sistem rejimi (Avtomatik)',
      'settings_theme_light': 'Açıq rejim',
      'settings_theme_dark': 'Qaranlıq rejim',
      'settings_lang_dialog_title': 'Dili seçin',
      'settings_close': 'Bağla',

      // Security Dialogs & Audit
      'sec_dialog_title': 'Təhlükəsizlik Auditi',
      'sec_dialog_intro': 'Tətbiq üzrə aparılmış təhlükəsizlik auditi və aktiv mühafizə parametrləri:',
      'sec_item_malware_title': 'Zərərli Proqram Filtrləməsi',
      'sec_item_malware_desc': '.apk, .exe, .bat, .vbs, .sh və digər 25+ icra olunan faylların QR koda çevrilməsi və açılması tam bloklanıb.',
      'sec_item_script_title': 'Skript & XSS Mühafizəsi',
      'sec_item_script_desc': 'javascript:, data:, file: kimi təhlükəli sistem protokolları və skript inyeksiyaları qadağan edilib.',
      'sec_item_scanner_title': 'Skaner Risk Təhlili',
      'sec_item_scanner_desc': 'Skan edilən hər bir kod real-vaxt rejimində təhlil edilir və şübhəli linklər barədə xəbərdarlıq verilir.',
      'sec_item_dos_title': 'Yaddaş və DoS Qorunması',
      'sec_item_dos_desc': 'QR kod generatorunda daşma və dondurma hücumlarının qarşısını almaq üçün 2953 simvol həddi tətbiq edilir.',
      'sec_item_privacy_title': 'Lokal Məxfilik (Zero-Knowledge)',
      'sec_item_privacy_desc': 'Bütün QR məlumatları yalnız lokal cihazda (SharedPreferences) saxlanılır, heç bir xarici serverə göndərilmir.',
      'sec_blocked_dialog_title': 'Təhlükəsizlik Qaydası Tətbiq Edildi',
      'sec_blocked_dialog_rule': 'Tətbiqin təhlükəsizlik qaydalarına əsasən icra qadağan edildi.',
      'sec_suspicious_dialog_title': 'Şübhəli Bağlantı Xəbərdarlığı',
      'sec_suspicious_dialog_btn_back': 'Geri Qayıt',
      'sec_suspicious_dialog_btn_proceed': 'Yenə də aç',
      'sec_understood': 'Anladım',

      // Ad banner
      'ad_tag': 'REKLAM',
      'ad_title_security': 'QR & Barkod Təhlükəsizliyi',
      'ad_sub_security': 'Zərərli proqramlardan və saxta linklərdən 100% qorunun.',
      'ad_title_premium': 'Premium QR Funksiyaları',
      'ad_sub_premium': 'Yüksək dəqiqlikli və rəngarəng QR kodlar yaradın.',
      'ad_cta_learn': 'Ətraflı',
      'ad_cta_explore': 'Kəşf et',
      'ad_close_tooltip': 'Reklamı gizlət',
    },

    // -------------------------------------------------------------
    // TURKISH
    // -------------------------------------------------------------
    'tr': {
      'nav_scanner': 'Tarayıcı',
      'nav_generator': 'Oluşturucu',
      'nav_history': 'Geçmiş',
      'nav_settings': 'Ayarlar',
      'scanner_title': 'QR Tarayıcı',
      'scanner_pick_gallery': 'Galeriden seç',
      'scanner_flash': 'Flaş',
      'scanner_switch_camera': 'Kamera değiştir',
      'scanner_no_qr_in_image': 'Seçilen görselde QR kod bulunamadı',
      'scanner_error_reading_image': 'Görsel okunurken hata: ',
      'scanner_result_title': 'QR Kod Okundu!',
      'scanner_security_clean': 'GÜVENLİK DENETİMİ: Temiz ve Güvenli',
      'scanner_security_suspicious': 'UYARI: Şüpheli Bağlantı',
      'scanner_security_blocked': 'TEHLİKE: Çalıştırma Engellendi',
      'scanner_rescan': 'Tekrar Tara',
      'scanner_copy': 'Kopyala',
      'scanner_share': 'Paylaş',
      'scanner_perm_denied': 'Kamera izni verilmedi.\nLütfen ayarlardan kamera iznini etkinleştirin.',
      'scanner_cam_unsupported': 'Kamera bu cihazda desteklenmiyor.',
      'scanner_cam_error': 'Kamera başlatılamadı.',
      'scanner_retry': 'Tekrar Dene',
      'action_open_browser': 'Tarayıcıda Aç',
      'action_open_whatsapp': 'WhatsApp\'ta Aç',
      'action_call': 'Ara',
      'action_send_email': 'E-posta Gönder',
      'action_send_sms': 'SMS Gönder',
      'action_copy_wifi': 'Wi-Fi Şifresini Kopyala',
      'action_copy_text': 'Metni Kopyala',
      'action_blocked_btn': 'Tehlikeli: Engellendi',
      'action_execute': 'Aç / Çalıştır',
      'action_copied': 'Panoya kopyalandı!',
      'action_wifi_copied': 'Wi-Fi şifresi kopyalandı!',
      'action_wifi_info_copied': 'Wi-Fi bilgisi kopyalandı!',
      'action_link_error': 'Bağlantı açılamadı',
      'action_call_error': 'Arama yapılamadı',
      'action_email_error': 'E-posta uygulaması bulunamadı',
      'action_sms_error': 'SMS uygulaması bulunamadı',
      'action_only_https': 'Güvenlik nedeniyle yalnızca HTTPS/HTTP bağlantıları açılabilir',
      'type_text': 'Düz Metin',
      'type_url': 'Web Sitesi',
      'type_whatsapp': 'WhatsApp',
      'type_wifi': 'Wi-Fi',
      'type_phone': 'Telefon',
      'type_email': 'E-posta',
      'type_sms': 'SMS',
      'gen_title': 'QR Oluşturucu',
      'gen_enter_details': 'QR kod oluşturmak için yukarıdaki alanı doldurun',
      'gen_color_picker': 'QR Kod Rengi:',
      'gen_save': 'Geçmişe Kaydet',
      'gen_share_img': 'Görseli Paylaş',
      'gen_saved_success': 'QR Kod geçmişe eklendi!',
      'gen_blocked_title': 'Oluşturma Engellendi',
      'gen_blocked_save_msg': 'Güvenlik Engeli: Tehlikeli içerik kaydedilemez!',
      'gen_blocked_share_msg': 'Zararlı içerik paylaşılamaz: ',
      'gen_status_clean': 'Güvenlik Denetimi: Temiz',
      'gen_status_suspicious': 'Şüpheli Bağlantı (Dikkatli olun)',
      'gen_input_text_label': 'Metin girin',
      'gen_input_text_hint': 'Örn: Merhaba, bu benim ilk QR kodum!',
      'gen_input_url_label': 'Web sitesi adresi',
      'gen_input_url_hint': 'https://example.com',
      'gen_input_wa_phone': 'WhatsApp Numarası (Ülke kodu ile)',
      'gen_input_wa_msg': 'Hazır Mesaj (İsteğe bağlı)',
      'gen_input_wa_msg_hint': 'Merhaba! İlanınızla ilgili yazıyorum...',
      'gen_input_wifi_ssid': 'Ağ Adı (SSID)',
      'gen_input_wifi_pass': 'Şifre',
      'gen_input_wifi_security': 'Güvenlik Türü',
      'gen_input_phone': 'Telefon Numarası',
      'gen_input_email': 'E-posta Adresi',
      'gen_input_subject': 'Konu',
      'gen_input_sms': 'SMS Mesajı',
      'gen_wifi_open': 'Açık (Şifresiz)',
      'history_title': 'Geçmiş',
      'history_clear_all_tooltip': 'Geçmişi temizle',
      'history_clear_dialog_title': 'Geçmişi temizle?',
      'history_clear_dialog_desc': 'Tüm kayıtlı QR kodlar silinecek. Bu işlem geri alınamaz.',
      'history_cancel': 'İptal',
      'history_delete': 'Sil',
      'history_search_hint': 'Geçmişte ara...',
      'history_filter_all': 'Tümü',
      'history_filter_scanned': 'Tarananlar',
      'history_filter_generated': 'Oluşturulanlar',
      'history_filter_favorites': 'Favoriler',
      'history_empty_title': 'Henüz QR kod yok',
      'history_empty_search_title': 'Sonuç bulunamadı',
      'history_empty_subtitle': 'Bir QR kod tarayın veya yeni bir tane oluşturun',
      'history_empty_search_subtitle': 'Farklı arama terimleri deneyin',
      'history_item_deleted': 'Öğe silindi',
      'history_undo': 'Geri al',
      'history_badge_scanned': '• Taranmış',
      'history_badge_generated': '• Oluşturulmuş',
      'settings_title': 'Ayarlar',
      'settings_section_appearance': 'GÖRÜNÜM VE DİL',
      'settings_theme_mode': 'Görünüm Modu',
      'settings_language': 'Dil / Language',
      'settings_section_storage': 'DEPOLAMA VE GEÇMİŞ',
      'settings_saved_items': 'Kayıtlı QR Kodlar',
      'settings_items_count': 'öğe kaydedildi',
      'settings_clear_btn': 'Temizle',
      'settings_cleared_msg': 'Geçmiş temizlendi',
      'settings_section_security': 'GÜVENLİK VE DENETİM',
      'settings_malware_protection': 'Zararlı Yazılım Koruması',
      'settings_malware_active': 'Aktif (.apk, .exe ve zararlı kodlar engellenir)',
      'settings_audit_report': 'Güvenlik Denetim Raporu',
      'settings_audit_report_sub': 'Güvenlik kuralları ve parametreleri görüntüle',
      'settings_section_about': 'HAKKINDA',
      'settings_version': 'Sürüm',
      'settings_privacy_policy': 'Gizlilik Politikası',
      'settings_privacy_policy_sub': 'Veri güvenliği ve izin rehberi',
      'settings_theme_dialog_title': 'Görünüm Modunu Seçin',
      'settings_theme_system': 'Sistem Varsayılanı (Otomatik)',
      'settings_theme_light': 'Açık Mod',
      'settings_theme_dark': 'Karanlık Mod',
      'settings_lang_dialog_title': 'Dil Seçin',
      'settings_close': 'Kapat',
      'sec_dialog_title': 'Güvenlik Denetimi',
      'sec_dialog_intro': 'Bu cihazda aktif güvenlik kuralları:',
      'sec_item_malware_title': 'Zararlı Yazılım Filtreleme',
      'sec_item_malware_desc': '.apk, .exe, .bat, .sh ve 25+ çalıştırılabilir dosya engellendi.',
      'sec_item_script_title': 'Komut Dosyası & XSS Koruması',
      'sec_item_script_desc': 'javascript:, data:, file: protokolleri yasaklandı.',
      'sec_item_scanner_title': 'Tarayıcı Risk Analizi',
      'sec_item_scanner_desc': 'Taranan her bağlantı anında denetlenir.',
      'sec_item_dos_title': 'Bellek Taşması Koruması',
      'sec_item_dos_desc': '2953 karakter sınırı kilitlenmeleri önler.',
      'sec_item_privacy_title': 'Yerel Gizlilik (Zero-Knowledge)',
      'sec_item_privacy_desc': 'Tüm veriler yalnızca cihazınızda saklanır.',
      'sec_blocked_dialog_title': 'Güvenlik Kuralı Devrede',
      'sec_blocked_dialog_rule': 'Güvenlik politikası gereğince işlem durduruldu.',
      'sec_suspicious_dialog_title': 'Şüpheli Bağlantı Uyarısı',
      'sec_suspicious_dialog_btn_back': 'Geri Dön',
      'sec_suspicious_dialog_btn_proceed': 'Yine de Aç',
      'sec_understood': 'Anladım',
      'ad_tag': 'REKLAM',
      'ad_title_security': 'QR & Barkod Güvenliği',
      'ad_sub_security': 'Zararlı yazılımlardan %100 korunun.',
      'ad_title_premium': 'Özelleştirilmiş QR Kodlar',
      'ad_sub_premium': 'Yüksek kaliteli ve renkli QR kodlar üretin.',
      'ad_cta_learn': 'Detaylar',
      'ad_cta_explore': 'Keşfet',
      'ad_close_tooltip': 'Reklamı gizle',
    },

    // -------------------------------------------------------------
    // SPANISH
    // -------------------------------------------------------------
    'es': {
      'nav_scanner': 'Escanear',
      'nav_generator': 'Generar',
      'nav_history': 'Historial',
      'nav_settings': 'Ajustes',
      'scanner_title': 'Escáner QR',
      'scanner_pick_gallery': 'Elegir de galería',
      'scanner_flash': 'Linterna',
      'scanner_switch_camera': 'Cambiar cámara',
      'scanner_no_qr_in_image': 'No se encontró ningún código QR en la imagen',
      'scanner_error_reading_image': 'Error al leer la imagen: ',
      'scanner_result_title': '¡Código QR Detectado!',
      'scanner_security_clean': 'AUDITORÍA: Seguro y Limpio',
      'scanner_security_suspicious': 'AVISO: Enlace Sospechoso',
      'scanner_security_blocked': 'PELIGRO: Ejecución Bloqueada',
      'scanner_rescan': 'Escanear de Nuevo',
      'scanner_copy': 'Copiar',
      'scanner_share': 'Compartir',
      'scanner_perm_denied': 'Permiso de cámara denegado.\nPor favor active el permiso en ajustes.',
      'scanner_cam_unsupported': 'Cámara no soportada en este dispositivo.',
      'scanner_cam_error': 'La cámara no está lista o está en uso.',
      'scanner_retry': 'Reintentar',
      'action_open_browser': 'Abrir en Navegador',
      'action_open_whatsapp': 'Abrir en WhatsApp',
      'action_call': 'Llamar',
      'action_send_email': 'Enviar Correo',
      'action_send_sms': 'Enviar SMS',
      'action_copy_wifi': 'Copiar Contraseña Wi-Fi',
      'action_copy_text': 'Copiar Texto',
      'action_blocked_btn': 'Peligroso: Bloqueado',
      'action_execute': 'Abrir / Ejecutar',
      'action_copied': '¡Copiado al portapapeles!',
      'action_wifi_copied': '¡Contraseña Wi-Fi copiada!',
      'action_wifi_info_copied': '¡Datos de Wi-Fi copiados!',
      'action_link_error': 'No se pudo abrir el enlace',
      'action_call_error': 'No se pudo iniciar la llamada',
      'action_email_error': 'No se encontró app de correo',
      'action_sms_error': 'No se encontró app de SMS',
      'action_only_https': 'Por seguridad, solo se admiten enlaces HTTPS/HTTP',
      'type_text': 'Texto Plano',
      'type_url': 'Sitio Web',
      'type_whatsapp': 'WhatsApp',
      'type_wifi': 'Red Wi-Fi',
      'type_phone': 'Teléfono',
      'type_email': 'Correo',
      'type_sms': 'SMS',
      'gen_title': 'Generador QR',
      'gen_enter_details': 'Complete el campo arriba para crear un código QR',
      'gen_color_picker': 'Color del Código QR:',
      'gen_save': 'Guardar',
      'gen_share_img': 'Compartir Imagen',
      'gen_saved_success': '¡Código QR guardado en historial!',
      'gen_blocked_title': 'Generación Bloqueada',
      'gen_blocked_save_msg': 'Seguridad: No se puede guardar contenido malicioso.',
      'gen_blocked_share_msg': 'No se puede compartir contenido peligroso: ',
      'gen_status_clean': 'Seguridad: Limpio y Seguro',
      'gen_status_suspicious': 'Contenido Sospechoso (Precaución)',
      'gen_input_text_label': 'Ingrese texto',
      'gen_input_text_hint': 'Ej: ¡Hola, este es mi código QR!',
      'gen_input_url_label': 'URL del sitio web',
      'gen_input_url_hint': 'https://ejemplo.com',
      'gen_input_wa_phone': 'Número de WhatsApp (con código país)',
      'gen_input_wa_msg': 'Mensaje predefinido (opcional)',
      'gen_input_wa_msg_hint': 'Hola, escribo por su anuncio...',
      'gen_input_wifi_ssid': 'Nombre de Red (SSID)',
      'gen_input_wifi_pass': 'Contraseña',
      'gen_input_wifi_security': 'Tipo de Seguridad',
      'gen_input_phone': 'Número de Teléfono',
      'gen_input_email': 'Dirección de Correo',
      'gen_input_subject': 'Asunto',
      'gen_input_sms': 'Mensaje SMS',
      'gen_wifi_open': 'Abierta (Sin contraseña)',
      'history_title': 'Historial',
      'history_clear_all_tooltip': 'Borrar historial',
      'history_clear_dialog_title': '¿Borrar historial?',
      'history_clear_dialog_desc': 'Se eliminarán todos los códigos QR guardados. No se puede deshacer.',
      'history_cancel': 'Cancelar',
      'history_delete': 'Eliminar',
      'history_search_hint': 'Buscar en historial...',
      'history_filter_all': 'Todos',
      'history_filter_scanned': 'Escaneados',
      'history_filter_generated': 'Generados',
      'history_filter_favorites': 'Favoritos',
      'history_empty_title': 'Aún no hay códigos QR',
      'history_empty_search_title': 'No se encontraron resultados',
      'history_empty_subtitle': 'Escanee o genere un nuevo código QR',
      'history_empty_search_subtitle': 'Pruebe con otras palabras clave',
      'history_item_deleted': 'Elemento eliminado',
      'history_undo': 'Deshacer',
      'history_badge_scanned': '• Escaneado',
      'history_badge_generated': '• Generado',
      'settings_title': 'Ajustes',
      'settings_section_appearance': 'APARIENCIA Y IDIOMA',
      'settings_theme_mode': 'Modo de Apariencia',
      'settings_language': 'Idioma / Language',
      'settings_section_storage': 'ALMACENAMIENTO',
      'settings_saved_items': 'Códigos QR Guardados',
      'settings_items_count': 'elementos guardados',
      'settings_clear_btn': 'Borrar',
      'settings_cleared_msg': 'Historial borrado',
      'settings_section_security': 'SEGURIDAD Y AUDITORÍA',
      'settings_malware_protection': 'Protección contra Malware',
      'settings_malware_active': 'Activa (.apk, .exe y scripts bloqueados)',
      'settings_audit_report': 'Informe de Seguridad',
      'settings_audit_report_sub': 'Ver reglas de seguridad activas',
      'settings_section_about': 'ACERCA DE',
      'settings_version': 'Versión',
      'settings_privacy_policy': 'Política de Privacidad',
      'settings_privacy_policy_sub': 'Seguridad de datos y permisos',
      'settings_theme_dialog_title': 'Seleccionar Modo',
      'settings_theme_system': 'Predeterminado del Sistema',
      'settings_theme_light': 'Modo Claro',
      'settings_theme_dark': 'Modo Oscuro',
      'settings_lang_dialog_title': 'Seleccionar Idioma',
      'settings_close': 'Cerrar',
      'sec_dialog_title': 'Auditoría de Seguridad',
      'sec_dialog_intro': 'Reglas de protección en este dispositivo:',
      'sec_item_malware_title': 'Filtro de Malware Ejecutable',
      'sec_item_malware_desc': 'Más de 25 extensiones ejecutables (.apk, .exe) bloqueadas.',
      'sec_item_script_title': 'Protección contra Scripts y XSS',
      'sec_item_script_desc': 'Protocolos peligrosos (javascript:, file:) prohibidos.',
      'sec_item_scanner_title': 'Evaluación en Tiempo Real',
      'sec_item_scanner_desc': 'Cada enlace escaneado se analiza al instante.',
      'sec_item_dos_title': 'Prevención de Saturación de Memoria',
      'sec_item_dos_desc': 'Límite seguro de 2953 caracteres para evitar bloqueos.',
      'sec_item_privacy_title': 'Privacidad Local (Zero-Knowledge)',
      'sec_item_privacy_desc': 'Todos los datos permanecen en su teléfono.',
      'sec_blocked_dialog_title': 'Regla de Seguridad Activada',
      'sec_blocked_dialog_rule': 'La acción fue bloqueada por políticas de seguridad.',
      'sec_suspicious_dialog_title': 'Aviso de Enlace Sospechoso',
      'sec_suspicious_dialog_btn_back': 'Volver',
      'sec_suspicious_dialog_btn_proceed': 'Continuar de todos modos',
      'sec_understood': 'Entendido',
      'ad_tag': 'PATROCINADO',
      'ad_title_security': 'Seguridad QR y Código de Barras',
      'ad_sub_security': 'Proteja su dispositivo contra virus y phishing.',
      'ad_title_premium': 'Códigos QR Personalizados',
      'ad_sub_premium': 'Cree códigos QR con colores de alta definición.',
      'ad_cta_learn': 'Saber más',
      'ad_cta_explore': 'Explorar',
      'ad_close_tooltip': 'Ocultar anuncio',
    },

    // -------------------------------------------------------------
    // RUSSIAN
    // -------------------------------------------------------------
    'ru': {
      'nav_scanner': 'Сканер',
      'nav_generator': 'Создать',
      'nav_history': 'История',
      'nav_settings': 'Настройки',
      'scanner_title': 'QR Сканер',
      'scanner_pick_gallery': 'Из галереи',
      'scanner_flash': 'Фонарик',
      'scanner_switch_camera': 'Сменить камеру',
      'scanner_no_qr_in_image': 'QR код на изображении не найден',
      'scanner_error_reading_image': 'Ошибка чтения изображения: ',
      'scanner_result_title': 'QR Код Обнаружен!',
      'scanner_security_clean': 'БЕЗОПАСНОСТЬ: Проверено и Чисто',
      'scanner_security_suspicious': 'ВНИМАНИЕ: Подозрительная ссылка',
      'scanner_security_blocked': 'ОПАСНО: Выполнение заблокировано',
      'scanner_rescan': 'Сканировать снова',
      'scanner_copy': 'Копировать',
      'scanner_share': 'Поделиться',
      'scanner_perm_denied': 'Доступ к камере отклонен.\nПожалуйста, включите разрешение в настройках.',
      'scanner_cam_unsupported': 'Камера не поддерживается на этом устройстве.',
      'scanner_cam_error': 'Камера занята другим приложением.',
      'scanner_retry': 'Повторить',
      'action_open_browser': 'Открыть в браузере',
      'action_open_whatsapp': 'Написать в WhatsApp',
      'action_call': 'Позвонить',
      'action_send_email': 'Отправить Email',
      'action_send_sms': 'Отправить SMS',
      'action_copy_wifi': 'Скопировать пароль Wi-Fi',
      'action_copy_text': 'Скопировать текст',
      'action_blocked_btn': 'Опасно: Заблокировано',
      'action_execute': 'Выполнить / Открыть',
      'action_copied': 'Скопировано в буфер!',
      'action_wifi_copied': 'Пароль Wi-Fi скопирован!',
      'action_wifi_info_copied': 'Данные Wi-Fi скопированы!',
      'action_link_error': 'Не удалось открыть ссылку',
      'action_call_error': 'Не удалось совершить вызов',
      'action_email_error': 'Приложение почты не найдено',
      'action_sms_error': 'Приложение SMS не найдено',
      'action_only_https': 'В целях безопасности открываются только HTTPS/HTTP ссылки',
      'type_text': 'Текст',
      'type_url': 'Веб-сайт',
      'type_whatsapp': 'WhatsApp',
      'type_wifi': 'Сеть Wi-Fi',
      'type_phone': 'Телефон',
      'type_email': 'Email',
      'type_sms': 'SMS',
      'gen_title': 'Генератор QR',
      'gen_enter_details': 'Заполните поле выше для создания QR кода',
      'gen_color_picker': 'Цвет QR Кода:',
      'gen_save': 'Сохранить',
      'gen_share_img': 'Поделиться фото',
      'gen_saved_success': 'QR код сохранен в историю!',
      'gen_blocked_title': 'Генерация заблокирована',
      'gen_blocked_save_msg': 'Блокировка: Нельзя сохранить опасный контент!',
      'gen_blocked_share_msg': 'Нельзя поделиться вредоносным контентом: ',
      'gen_status_clean': 'Проверка безопасности: Чисто',
      'gen_status_suspicious': 'Подозрительный контент (Будьте осторожны)',
      'gen_input_text_label': 'Введите текст',
      'gen_input_text_hint': 'Например: Привет, это мой первый QR код!',
      'gen_input_url_label': 'Адрес сайта (URL)',
      'gen_input_url_hint': 'https://example.com',
      'gen_input_wa_phone': 'Номер WhatsApp (с кодом страны)',
      'gen_input_wa_msg': 'Готовое сообщение (необязательно)',
      'gen_input_wa_msg_hint': 'Здравствуйте! Пишу по поводу объявления...',
      'gen_input_wifi_ssid': 'Имя сети (SSID)',
      'gen_input_wifi_pass': 'Пароль',
      'gen_input_wifi_security': 'Тип защиты',
      'gen_input_phone': 'Номер телефона',
      'gen_input_email': 'Email адрес',
      'gen_input_subject': 'Тема письма',
      'gen_input_sms': 'Текст SMS',
      'gen_wifi_open': 'Открытая (Без пароля)',
      'history_title': 'История',
      'history_clear_all_tooltip': 'Очистить историю',
      'history_clear_dialog_title': 'Очистить историю?',
      'history_clear_dialog_desc': 'Все сохраненные QR коды будут удалены безвозвратно.',
      'history_cancel': 'Отмена',
      'history_delete': 'Удалить',
      'history_search_hint': 'Поиск в истории...',
      'history_filter_all': 'Все',
      'history_filter_scanned': 'Сканированные',
      'history_filter_generated': 'Созданные',
      'history_filter_favorites': 'Избранное',
      'history_empty_title': 'История пуста',
      'history_empty_search_title': 'Ничего не найдено',
      'history_empty_subtitle': 'Отсканируйте или создайте новый QR код',
      'history_empty_search_subtitle': 'Попробуйте изменить запрос',
      'history_item_deleted': 'Элемент удален',
      'history_undo': 'Вернуть',
      'history_badge_scanned': '• Отсканирован',
      'history_badge_generated': '• Создан',
      'settings_title': 'Настройки',
      'settings_section_appearance': 'ВНЕШНИЙ ВИД И ЯЗЫК',
      'settings_theme_mode': 'Тема оформления',
      'settings_language': 'Язык / Language',
      'settings_section_storage': 'ПАМЯТЬ И ДАННЫЕ',
      'settings_saved_items': 'Сохраненные QR коды',
      'settings_items_count': 'элементов в памяти',
      'settings_clear_btn': 'Очистить',
      'settings_cleared_msg': 'История очищена',
      'settings_section_security': 'БЕЗОПАСНОСТЬ И АУДИТ',
      'settings_malware_protection': 'Защита от вредоносных программ',
      'settings_malware_active': 'Активна (.apk, .exe и скрипты блокируются)',
      'settings_audit_report': 'Отчет о безопасности',
      'settings_audit_report_sub': 'Параметры защиты и правила аудита',
      'settings_section_about': 'О ПРИЛОЖЕНИИ',
      'settings_version': 'Версия',
      'settings_privacy_policy': 'Политика конфиденциальности',
      'settings_privacy_policy_sub': 'Безопасность данных и разрешения',
      'settings_theme_dialog_title': 'Выберите тему',
      'settings_theme_system': 'Системная (Авто)',
      'settings_theme_light': 'Светлая тема',
      'settings_theme_dark': 'Темная тема',
      'settings_lang_dialog_title': 'Выберите язык',
      'settings_close': 'Закрыть',
      'sec_dialog_title': 'Аудит безопасности',
      'sec_dialog_intro': 'Параметры активной защиты на устройстве:',
      'sec_item_malware_title': 'Фильтрация вредоносного ПО',
      'sec_item_malware_desc': 'Более 25 опасных исполняемых файлов (.apk, .exe) заблокированы.',
      'sec_item_script_title': 'Защита от скриптов и XSS',
      'sec_item_script_desc': 'Опасные протоколы (javascript:, file:) запрещены.',
      'sec_item_scanner_title': 'Оценка риска в реальном времени',
      'sec_item_scanner_desc': 'Каждая ссылка мгновенно анализируется.',
      'sec_item_dos_title': 'Защита от переполнения буфера',
      'sec_item_dos_desc': 'Лимит в 2953 символа предотвращает зависание.',
      'sec_item_privacy_title': 'Локальная приватность (Zero-Knowledge)',
      'sec_item_privacy_desc': 'Все данные остаются исключительно на устройстве.',
      'sec_blocked_dialog_title': 'Сработало правило безопасности',
      'sec_blocked_dialog_rule': 'Действие заблокировано согласно политике безопасности.',
      'sec_suspicious_dialog_title': 'Предупреждение о подозрительной ссылке',
      'sec_suspicious_dialog_btn_back': 'Назад',
      'sec_suspicious_dialog_btn_proceed': 'Все равно открыть',
      'sec_understood': 'Понятно',
      'ad_tag': 'СПОНСОР',
      'ad_title_security': 'Безопасность QR и штрихкодов',
      'ad_sub_security': '100% защита от вредоносных программ и фишинга.',
      'ad_title_premium': 'Цветные QR Коды',
      'ad_sub_premium': 'Создавайте персонализированные QR коды высокой четкости.',
      'ad_cta_learn': 'Подробнее',
      'ad_cta_explore': 'Узнать',
      'ad_close_tooltip': 'Скрыть рекламу',
    },

    // -------------------------------------------------------------
    // GERMAN
    // -------------------------------------------------------------
    'de': {
      'nav_scanner': 'Scannen',
      'nav_generator': 'Erstellen',
      'nav_history': 'Verlauf',
      'nav_settings': 'Einstellungen',
      'scanner_title': 'QR Scanner',
      'scanner_pick_gallery': 'Aus Galerie wählen',
      'scanner_flash': 'Taschenlampe',
      'scanner_switch_camera': 'Kamera wechseln',
      'scanner_no_qr_in_image': 'Kein QR-Code im Bild gefunden',
      'scanner_error_reading_image': 'Fehler beim Lesen des Bildes: ',
      'scanner_result_title': 'QR-Code erkannt!',
      'scanner_security_clean': 'SICHERHEITSPRÜFUNG: Sicher',
      'scanner_security_suspicious': 'WARNUNG: Verdächtiger Link',
      'scanner_security_blocked': 'GEFAHR: Ausführung blockiert',
      'scanner_rescan': 'Erneut scannen',
      'scanner_copy': 'Kopieren',
      'scanner_share': 'Teilen',
      'scanner_perm_denied': 'Kamerazugriff verweigert.\nBitte in den Einstellungen aktivieren.',
      'scanner_cam_unsupported': 'Kamera wird nicht unterstützt.',
      'scanner_cam_error': 'Kamera nicht bereit.',
      'scanner_retry': 'Erneut versuchen',
      'action_open_browser': 'Im Browser öffnen',
      'action_open_whatsapp': 'In WhatsApp öffnen',
      'action_call': 'Anrufen',
      'action_send_email': 'E-Mail senden',
      'action_send_sms': 'SMS senden',
      'action_copy_wifi': 'WLAN-Passwort kopieren',
      'action_copy_text': 'Text kopieren',
      'action_blocked_btn': 'Gefahr: Blockiert',
      'action_execute': 'Öffnen / Ausführen',
      'action_copied': 'In die Zwischenablage kopiert!',
      'action_wifi_copied': 'WLAN-Passwort kopiert!',
      'action_wifi_info_copied': 'WLAN-Daten kopiert!',
      'action_link_error': 'Link konnte nicht geöffnet werden',
      'action_call_error': 'Anruf fehlgeschlagen',
      'action_email_error': 'Keine E-Mail-App gefunden',
      'action_sms_error': 'Keine SMS-App gefunden',
      'action_only_https': 'Aus Sicherheitsgründen werden nur HTTPS/HTTP-Links unterstützt',
      'type_text': 'Reiner Text',
      'type_url': 'Webseite',
      'type_whatsapp': 'WhatsApp',
      'type_wifi': 'WLAN-Netzwerk',
      'type_phone': 'Telefonnummer',
      'type_email': 'E-Mail',
      'type_sms': 'SMS',
      'gen_title': 'QR Generator',
      'gen_enter_details': 'Füllen Sie das obige Feld aus, um einen QR-Code zu erstellen',
      'gen_color_picker': 'QR-Code Farbe:',
      'gen_save': 'Speichern',
      'gen_share_img': 'Bild teilen',
      'gen_saved_success': 'QR-Code im Verlauf gespeichert!',
      'gen_blocked_title': 'Erstellung blockiert',
      'gen_blocked_save_msg': 'Sicherheit: Gefährlicher Inhalt kann nicht gespeichert werden.',
      'gen_blocked_share_msg': 'Gefährlicher Inhalt kann nicht geteilt werden: ',
      'gen_status_clean': 'Sicherheitsprüfung: Sicher',
      'gen_status_suspicious': 'Verdächtiger Inhalt (Vorsicht)',
      'gen_input_text_label': 'Text eingeben',
      'gen_input_text_hint': 'z.B.: Hallo, das ist mein QR-Code!',
      'gen_input_url_label': 'Webseiten-URL',
      'gen_input_url_hint': 'https://beispiel.de',
      'gen_input_wa_phone': 'WhatsApp-Nummer (mit Ländercode)',
      'gen_input_wa_msg': 'Vorgefertigte Nachricht (optional)',
      'gen_input_wa_msg_hint': 'Hallo! Ich melde mich bezüglich...',
      'gen_input_wifi_ssid': 'Netzwerkname (SSID)',
      'gen_input_wifi_pass': 'Passwort',
      'gen_input_wifi_security': 'Sicherheitstyp',
      'gen_input_phone': 'Telefonnummer',
      'gen_input_email': 'E-Mail-Adresse',
      'gen_input_subject': 'Betreff',
      'gen_input_sms': 'SMS-Nachricht',
      'gen_wifi_open': 'Offen (Kein Passwort)',
      'history_title': 'Verlauf',
      'history_clear_all_tooltip': 'Verlauf leeren',
      'history_clear_dialog_title': 'Verlauf leeren?',
      'history_clear_dialog_desc': 'Alle gespeicherten QR-Codes werden unwiderruflich gelöscht.',
      'history_cancel': 'Abbrechen',
      'history_delete': 'Löschen',
      'history_search_hint': 'Im Verlauf suchen...',
      'history_filter_all': 'Alle',
      'history_filter_scanned': 'Gescannte',
      'history_filter_generated': 'Erstellte',
      'history_filter_favorites': 'Favoriten',
      'history_empty_title': 'Noch keine QR-Codes',
      'history_empty_search_title': 'Keine Ergebnisse gefunden',
      'history_empty_subtitle': 'Scannen oder erstellen Sie einen QR-Code',
      'history_empty_search_subtitle': 'Versuchen Sie andere Suchbegriffe',
      'history_item_deleted': 'Element gelöscht',
      'history_undo': 'Rückgängig',
      'history_badge_scanned': '• Gescannt',
      'history_badge_generated': '• Erstellt',
      'settings_title': 'Einstellungen',
      'settings_section_appearance': 'DARSTELLUNG & SPRACHE',
      'settings_theme_mode': 'Darstellungsmodus',
      'settings_language': 'Sprache / Language',
      'settings_section_storage': 'SPEICHER & DATEN',
      'settings_saved_items': 'Gespeicherte QR-Codes',
      'settings_items_count': 'Elemente gespeichert',
      'settings_clear_btn': 'Leeren',
      'settings_cleared_msg': 'Verlauf geleert',
      'settings_section_security': 'SICHERHEIT & AUDIT',
      'settings_malware_protection': 'Schutz vor Schadsoftware',
      'settings_malware_active': 'Aktiv (.apk, .exe und bösartige Skripte blockiert)',
      'settings_audit_report': 'Sicherheitsbericht',
      'settings_audit_report_sub': 'Aktive Schutzregeln anzeigen',
      'settings_section_about': 'ÜBER DIE APP',
      'settings_version': 'Version',
      'settings_privacy_policy': 'Datenschutzerklärung',
      'settings_privacy_policy_sub': 'Datenschutz und Berechtigungen',
      'settings_theme_dialog_title': 'Modus wählen',
      'settings_theme_system': 'Systemstandard (Automatisch)',
      'settings_theme_light': 'Heller Modus',
      'settings_theme_dark': 'Dunkler Modus',
      'settings_lang_dialog_title': 'Sprache wählen',
      'settings_close': 'Schließen',
      'sec_dialog_title': 'Sicherheitsaudit',
      'sec_dialog_intro': 'Aktive Schutzfunktionen auf diesem Gerät:',
      'sec_item_malware_title': 'Schadsoftware-Filter',
      'sec_item_malware_desc': 'Über 25 ausführbare Dateitypen (.apk, .exe) blockiert.',
      'sec_item_script_title': 'Skript- & XSS-Schutz',
      'sec_item_script_desc': 'Gefährliche Schemata (javascript:, file:) verboten.',
      'sec_item_scanner_title': 'Echtzeit-Risikoanalyse',
      'sec_item_scanner_desc': 'Jeder gescannte Link wird sofort überprüft.',
      'sec_item_dos_title': 'Pufferüberlauf-Schutz',
      'sec_item_dos_desc': 'Sicheres 2953-Zeichen-Limit verhindert Abstürze.',
      'sec_item_privacy_title': 'Lokaler Datenschutz (Zero-Knowledge)',
      'sec_item_privacy_desc': 'Alle Daten verbleiben vollständig auf Ihrem Gerät.',
      'sec_blocked_dialog_title': 'Sicherheitsregel ausgelöst',
      'sec_blocked_dialog_rule': 'Die Ausführung wurde gemäß den Richtlinien blockiert.',
      'sec_suspicious_dialog_title': 'Warnung: Verdächtiger Link',
      'sec_suspicious_dialog_btn_back': 'Zurück',
      'sec_suspicious_dialog_btn_proceed': 'Trotzdem fortfahren',
      'sec_understood': 'Verstanden',
      'ad_tag': 'WERBUNG',
      'ad_title_security': 'QR- & Barcode-Sicherheit',
      'ad_sub_security': '100% Schutz vor Malware und Phishing-Links.',
      'ad_title_premium': 'Farbige QR-Codes',
      'ad_sub_premium': 'Erstellen Sie hochauflösende individuelle QR-Codes.',
      'ad_cta_learn': 'Mehr erfahren',
      'ad_cta_explore': 'Entdecken',
      'ad_close_tooltip': 'Werbung verbergen',
    },
  };
}

/// Widget-lər daxilində rahatlıqla `context.tr('key')` yazmaq üçün extension
extension LocalizationExtension on BuildContext {
  String tr(String key) => AppStrings.get(key);
}
